apiVersion: v1
kind: Service
metadata:
  name: influxdb

spec:
  selector:
    app.kubernetes.io/component: influxdb
    app.kubernetes.io/instance: influxdb
    app.kubernetes.io/name: influxdb
  type: NodePort
  ports:
    - name: http
      port: 8086
      targetPort: http
      nodePort: 30086
    - name: rpc
      port: 8088
      targetPort: rpc
      nodePort: 30088
