apiVersion: authentik.starry.blue/v1alpha1
kind: AuthentikApplication
metadata:
  name: traefik

spec:
  access:
    rules:
      - group:
          name: Admin
  adopt: IfMatch
  group: System
  icon: https://raw.githubusercontent.com/traefik/traefik/master/docs/content/assets/img/traefik.logo.png
  name: Traefik
  provider:
    name: Traefik
    flows:
      authentication:
        slug: sign-in
      authorization:
        slug: authorize
      invalidation:
        slug: default-provider-invalidation-flow
    proxy:
      accessTokenValidity: days=1
      forwardAuthSingle:
        externalHost: https://traefik.starry.blue
      interceptHeaderAuth: true
      outpost:
        name: authentik Embedded Outpost
      refreshTokenValidity: days=30
  slug: traefik

---

apiVersion: authentik.starry.blue/v1alpha1
kind: AuthentikApplication
metadata:
  name: router

spec:
  access:
    rules:
      - group:
          name: Admin
  group: System
  name: Router
  provider:
    name: Router
    flows:
      authentication:
        slug: sign-in
      authorization:
        slug: authorize
      invalidation:
        slug: default-provider-invalidation-flow
    proxy:
      accessTokenValidity: days=1
      forwardAuthSingle:
        externalHost: https://router.starry.blue
      interceptHeaderAuth: true
      outpost:
        name: authentik Embedded Outpost
      refreshTokenValidity: days=30
  slug: router
