apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nebula

images:
  - name: docker.io/bitnami/postgresql
    newName: ghcr.io/slashnephy/nebula-postgres
    newTag: main@sha256:32c213e61c462bb48dd0f02f15391e387b496b3e18d0251e1db7b12b28cd6991
  - name: docker.io/bitnami/os-shell
    newName: docker.io/bitnamilegacy/os-shell

helmCharts:
  - name: postgresql
    releaseName: postgresql
    version: 16.7.27
    repo: oci://registry-1.docker.io/bitnamicharts
    valuesInline:
      auth:
        database: nebula
        existingSecret: postgresql-secret
        username: nebula
      backup:
        cronjob:
          concurrencyPolicy: Forbid
          containerSecurityContext:
            runAsGroup: 1000
            runAsUser: 1000
          restartPolicy: Never
          # @hourly
          schedule: "20 * * * *"
          storage:
            existingClaim: nebula-postgresql-backup
          timeZone: Asia/Tokyo
        enabled: true
      global:
        imagePullSecrets:
          - ghcr-io-credentials
      primary:
        extraEnvVars:
          - name: TZ
            value: Asia/Tokyo
        extraVolumeMounts:
          - name: var-run
            mountPath: /var/run/postgresql
        extraVolumes:
          - name: var-run
            emptyDir: {}
        persistence:
          existingClaim: nebula-postgresql-data
        resourcesPreset: large
        service:
          nodePorts:
            postgresql: 5432
          type: NodePort
      tls:
        autoGenerated: true
        enabled: true
  - name: redis
    releaseName: redis
    version: 25.3.9
    repo: oci://registry-1.docker.io/bitnamicharts
    valuesInline:
      architecture: standalone
      auth:
        existingSecret: redis-secret
      global:
        imageRegistry: public.ecr.aws
        security:
          # imageRegistry を変更するために必要
          allowInsecureImages: true
      master:
        extraEnvVars:
          - name: TZ
            value: Asia/Tokyo
        persistence:
          existingClaim: nebula-redis-data
        resourcesPreset: nano

resources:
  - ./../../common/registry-ghcr-io/lily
  - ./resources/cronjob-cleanup-backup.yaml
  - ./resources/deployment-backend.yaml
  - ./resources/deployment-frontend.yaml
  - ./resources/deployment-ml.yaml
  - ./resources/deployment-river-ui.yaml
  - ./resources/dns.yaml
  - ./resources/ingress.yaml
  - ./resources/namespace.yaml
  - ./resources/secret.yaml
  - ./resources/service.yaml
  - ./resources/volume-backup.yaml
  - ./resources/volume-redis.yaml
  - ./resources/volume.yaml

configMapGenerator:
  - name: backend-config
    literals:
      - SERVER_ORIGIN=https://nebula.starry.blue
      - ML_BASE_URL=http://ml:8083
