apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nebula

images:
  - name: docker.io/bitnami/postgresql
    newName: ghcr.io/slashnephy/nebula-postgres
    newTag: main@sha256:6da8f2983b93a30d4b606471b98ef3e8975ac2dcd80afc0ec075868cb35073c0
  - name: docker.io/bitnami/os-shell
    newName: docker.io/bitnamilegacy/os-shell

helmCharts:
  - name: postgresql
    releaseName: postgresql
    version: 18.7.0
    repo: oci://registry-1.docker.io/bitnamicharts
    valuesInline:
      auth:
        database: nebula
        existingSecret: postgresql-secret
        username: nebula
      global:
        imagePullSecrets:
          - ghcr-io-credentials
      primary:
        extraEnvVars:
          - name: TZ
            value: Asia/Tokyo
        extraVolumeMounts:
          - name: var-run
            mountPath: /var/run/postgresql
        extraVolumes:
          - name: var-run
            emptyDir: {}
        persistence:
          existingClaim: nebula-postgresql-data
        resourcesPreset: xlarge
        service:
          nodePorts:
            postgresql: 5432
          type: NodePort
      tls:
        autoGenerated: true
        enabled: true
  - name: redis
    releaseName: redis
    version: 25.5.3
    repo: oci://registry-1.docker.io/bitnamicharts
    valuesInline:
      architecture: standalone
      auth:
        existingSecret: redis-secret
      global:
        imageRegistry: public.ecr.aws
        security:
          # imageRegistry を変更するために必要
          allowInsecureImages: true
      master:
        extraEnvVars:
          - name: TZ
            value: Asia/Tokyo
        persistence:
          existingClaim: nebula-redis-data
        resourcesPreset: nano

resources:
  - ./../../common/registry-ghcr-io/lily
  - ./resources/cronjob-backup-contents.yaml
  - ./resources/cronjob-backup-database.yaml
  - ./resources/deployment-backend.yaml
  - ./resources/deployment-ffmpeg.yaml
  - ./resources/deployment-frontend.yaml
  - ./resources/deployment-instagram.yaml
  - ./resources/deployment-ml.yaml
  - ./resources/deployment-river-ui.yaml
  - ./resources/deployment-worker.yaml
  - ./resources/deployment-xctid.yaml
  - ./resources/deployment-ytdlp.yaml
  - ./resources/dns.yaml
  - ./resources/ingress.yaml
  - ./resources/namespace.yaml
  - ./resources/secret.yaml
  - ./resources/service.yaml
  - ./resources/volume-postgresql.yaml
  - ./resources/volume-redis.yaml

configMapGenerator:
  - name: backend-config
    literals:
      - SERVER_ORIGIN=https://nebula.starry.blue
      - FRONTEND_ORIGIN=https://nebula.starry.blue
      - COOKIE_DOMAIN=nebula.starry.blue
      - MEDIA_STORAGE_LOCAL_DIRECTORY=/app/media
      - AVATAR_STORAGE_LOCAL_DIRECTORY=/app/avatars
      - THUMBNAIL_STORAGE_LOCAL_DIRECTORY=/app/thumbnails
      - ML_BASE_URL=http://ml:8083
      - XCTID_BASE_URL=http://xctid:8084
      - INSTAGRAM_BASE_URL=http://instagram:8085
      - YTDLP_BASE_URL=http://ytdlp:8086
      - FFMPEG_BASE_URL=http://ffmpeg:8087
