apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob

spec:
  schedule: "0 7 * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: app
              image: ghcr.io/slashnephy/auto-claimer:latest@sha256:26bc60ab91f0a958e906ab8242c5410e8d5307e3fc6cafe8c7537f74c28d8e8e
              env:
                - name: DATABASE_DSN
                  value: /data/auto-claimer.db
              envFrom:
                - secretRef:
                    name: app-secret
              volumeMounts:
                - name: data
                  mountPath: /data
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
          volumes:
            - name: data
              hostPath:
                path: /mnt/local/auto-claimer
                type: Directory
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
