apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob

spec:
  schedule: "0 7 * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: app
              image: ghcr.io/slashnephy/auto-claimer:latest@sha256:48522dbcd439ca1d29d6ed3158f67c0e8a20297077bc5bcf4979088a5de42110
              env:
                - name: DATABASE_DSN
                  value: /data/auto-claimer.db
              envFrom:
                - secretRef:
                    name: app-secret
              volumeMounts:
                - name: data
                  mountPath: /data
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
          volumes:
            - name: data
              hostPath:
                path: /mnt/local/auto-claimer
                type: Directory
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
  concurrencyPolicy: Forbid
