apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob

spec:
  schedule: "0 7 * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: app
              image: ghcr.io/slashnephy/auto-claimer:latest@sha256:9ac6fa8fccfc9dc3a80d8c0fcd69ee858a1d233738db5d2cbafefa44aedfd756
              env:
                - name: DATABASE_DSN
                  value: /data/auto-claimer.db
              envFrom:
                - secretRef:
                    name: app-secret
              volumeMounts:
                - name: data
                  mountPath: /data
              securityContext:
                allowPrivilegeEscalation: false
          volumes:
            - name: data
              hostPath:
                path: /mnt/local/auto-claimer
                type: Directory
          restartPolicy: Never
  concurrencyPolicy: Forbid
