apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

helmCharts:
  # https://github.com/kubernetes-sigs/external-dns/tree/master/charts/external-dns
  - name: external-dns
    releaseName: external-dns
    namespace: external-dns
    version: 1.20.0
    repo: https://kubernetes-sigs.github.io/external-dns
    includeCRDs: true
    valuesInline:
      provider:
        name: cloudflare
      sources:
        - crd
      policy: sync
      env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: external-dns-secret
              key: cloudflare-api-token

resources:
  - ./resources/secret.yaml
