apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: app
          image: ghcr.io/gotson/komga:1.24.3@sha256:517033528928003d730e6d3ae99c74470e23938e3f3954924a60dd069bd28c5a
          env:
            - name: TZ
              value: Asia/Tokyo
          ports:
            - containerPort: 25600
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 1000
            runAsUser: 1000
      volumes:
        - name: config
          hostPath:
            path: /mnt/local/komga/config
            type: DirectoryOrCreate
        - name: data
          hostPath:
            path: /mnt/pool/books
            type: Directory
      restartPolicy: Always
