apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-cd

helmCharts:
  # https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
  - name: argo-cd
    releaseName: argo-cd
    namespace: argo-cd
    version: 9.5.0
    repo: https://argoproj.github.io/argo-helm
    valuesInline:
      applicationSet:
        metrics:
          enabled: true
        # Telegraf は Pod Annotation による検出しかサポートしていない
        podAnnotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "8080"

          prometheus.io/scheme: http
          prometheus.io/scrape: "true"
      controller:
        metrics:
          enabled: true
        # Telegraf は Pod Annotation による検出しかサポートしていない
        podAnnotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "8082"
          prometheus.io/scheme: http
          prometheus.io/scrape: "true"
      dex:
        initContainers:
          - name: wait-for-authentik
            args:
              - --url
              - https://id.starry.blue/application/o/argo-cd/
            image: ghcr.io/slashnephy/wait-for:master@sha256:2d9df5eadb6d2a8273aec1dba550571e79d85bd555a11d843dedd078633f91b6
        metrics:
          enabled: true
        # Telegraf は Pod Annotation による検出しかサポートしていない
        podAnnotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "5558"
          prometheus.io/scheme: http
          prometheus.io/scrape: "true"
      global:
        addPrometheusAnnotations: true
      notifications:
        logFormat: json
        logLevel: warn
        metrics:
          enabled: true
        # Telegraf は Pod Annotation による検出しかサポートしていない
        podAnnotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "9001"
          prometheus.io/scheme: http
          prometheus.io/scrape: "true"
      repoServer:
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 30
          timeoutSeconds: 5
        metrics:
          enabled: true
        # Telegraf は Pod Annotation による検出しかサポートしていない
        podAnnotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "8084"
          prometheus.io/scheme: http
          prometheus.io/scrape: "true"
        replicas: 2
      server:
        extensions:
          enabled: true
        metrics:
          enabled: true
        # Telegraf は Pod Annotation による検出しかサポートしていない
        podAnnotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "8083"
          prometheus.io/scheme: http
          prometheus.io/scrape: "true"
        service:
          nodePortHttp: 30000
          nodePortHttps: 30001
          type: NodePort
resources:
  - ./resources/application-private.yaml
  - ./resources/application-set-lily.yaml
  - ./resources/dns.yaml
  - ./resources/ingress.yaml
  - ./resources/namespace.yaml
  - ./resources/projects.yaml
  - ./resources/secret.yaml
  # - ./resources/secret-bbc.yaml
  # - ./resources/application-set-bbc.yaml
  # - ./resources/service-bbc.yaml

patches:
  - path: ./resources/patch-argocd-cm.yaml
  - path: ./resources/patch-argocd-cmd-params-cm.yaml
  - path: ./resources/patch-argocd-notifications-cm.yaml
  - path: ./resources/patch-argocd-rbac-cm.yaml
  # enable exec
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      name: argo-cd-argocd-server
    patch: |-
      - op: add
        path: /rules/-
        value:
          apiGroups:
            - ""
          resources:
            - pods/exec
          verbs:
            - create
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: argo-cd-argocd-server
    patch: |-
      - op: add
        path: /rules/-
        value:
          apiGroups:
            - ""
          resources:
            - pods/exec
          verbs:
            - create
