apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: app
          image: public.ecr.aws/amazoncorretto/amazoncorretto:8-al2023-jre@sha256:891d047ab04e13d69fec8b35aa5fbf5a78c3b73a0f1d6d15f47c83f29f1cf649
          workingDir: /app
          args:
            - java
            - -jar
            - forge-1.12.2-14.23.5.2860.jar
          env:
            - name: TZ
              value: Asia/Tokyo
          ports:
            - containerPort: 25565
            - containerPort: 8123
          volumeMounts:
            - name: data
              mountPath: /app
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: data
          hostPath:
            path: /mnt/local/minecraft/forge_1.12.2
            type: Directory
      restartPolicy: Always
      securityContext:
        seccompProfile:
          type: RuntimeDefault
