apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: dns

spec:
  endpoints:
    - dnsName: mc.starry.blue
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"
      recordTTL: 1 # Auto
      recordType: CNAME
      targets:
        - gateway.starry.blue
