apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cron-backup-node

resources:
  - ./resources/cronjob.yaml
  - ./resources/namespace.yaml
  - ./resources/role.yaml
  - ./resources/service-account.yaml
