apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob

spec:
  schedule: "0 4 * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: app
              image: public.ecr.aws/debian/debian:stable-slim@sha256:b9aa232805c09779c96307c9e07716648e07218950aa083ca60b0357864c6ff0
              command:
                - bash
                - -c
                - find /target -empty -delete
              volumeMounts:
                - name: target
                  mountPath: /target
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
          volumes:
            - name: target
              hostPath:
                path: /mnt/pool/records
                type: Directory
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
  concurrencyPolicy: Forbid
