apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: route

spec:
  routes:
    - kind: Rule
      match: Host(`dify.starry.blue`) && (PathPrefix(`/console/api`) || PathPrefix(`/api`) || PathPrefix(`/v1`) || PathPrefix(`/files`))
      services:
        - name: dify-api-svc
          port: api
    - kind: Rule
      match: Host(`dify.starry.blue`)
      services:
        - name: dify-web-svc
          port: web
