apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dify-api-secret

type: Opaque
spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/pbvh6ygyso2xax2sikwkkntwbu

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dify-plugin-connector-secret

type: Opaque
spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/n52dbzucmtfukop7z74gasztuy


---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dify-plugin-daemon-secret

type: Opaque
spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/iutydswoaforjfw4ybxnmv66me

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dify-postgresql

type: Opaque
spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/7dlvgg5dacwu446tiqwxqroufa

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dify-redis

type: Opaque
spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/e5eqxaunhxbd4l4fudv47u5xja

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dify-sandbox-secret

type: Opaque
spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/erm44pfuo4fixtjt2qn3wm5pei

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dify-shared-celery-secret

type: Opaque
spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/t5ld63z6ymq2v7qqna3jk2ksmy

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dify-shared-db-secret

type: Opaque
spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/adcxpe6hwit46l4htk65eojgva

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dify-shared-mail-secret

type: Opaque
spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/6qzlbceonangdn6bvywa5i5z74

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dify-shared-redis-secret

type: Opaque
spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/ienkl747prxao43ihe5yuybct4

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dify-shared-storage-secret

type: Opaque
spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/eodxa4q2nujpbkrnkqybfimmky

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dify-shared-vectordb-secret

type: Opaque
spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/7yru3aoy36tj4u67binscwbyem

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dify-worker-beat-secret

type: Opaque
spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/m42g7m65leaacgiurcvz3ltfn4

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dify-worker-secret

type: Opaque
spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/7qfykz73f5lvtgon2javgzc2eq
