apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dify-secret

spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/e5m5nho22flv6d2jj6mwlqtn7u

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dify-postgresql

spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/n6qwmwli35p55bh6tbpn7webpa

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dify-redis

spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/fotz6fgjtiqdz2tljuimyhu2fy
