apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: app
          image: codercom/code-server:4.19.1-bullseye@sha256:993c381c28a3738b903ac21180f5f9dab8f2aa547bbb0b9d69bea558691e10d3
          workingDir: /mnt
          args:
            - --auth=none
            - --disable-telemetry
          env:
            - name: TZ
              value: Asia/Tokyo
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: pool
              mountPath: /mnt/pool
            - name: local
              mountPath: /mnt/local
            - name: data
              mountPath: /home/coder/.local/share/code-server
            - name: config
              mountPath: /home/coder/.config
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: pool
          hostPath:
            path: /mnt/pool
            type: Directory
        - name: local
          hostPath:
            path: /mnt/local
            type: Directory
        - name: data
          hostPath:
            path: /mnt/local/code-server/data
            type: DirectoryOrCreate
        - name: config
          emptyDir: {}
      restartPolicy: Always
      securityContext:
        seccompProfile:
          type: RuntimeDefault
