apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup

spec:
  schedule: "0 * * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: pic-table
              image: public.ecr.aws/docker/library/mongo:7.0.34-jammy@sha256:80bdab05c3cdc7c233438f70553960e86112e0fc9d46f0409ee03fc796bb24b7
              command:
                - bash
                - -c
                - |
                  mongoexport \
                    --uri="mongodb://$MONGODB_USER:$MONGODB_PASSWORD@db:27017/stella?authSource=admin" \
                    --collection=$MONGODB_COLLECTION \
                    --out /backup/${MONGODB_COLLECTION}.json
              env:
                - name: MONGODB_USER
                  valueFrom:
                    secretKeyRef:
                      name: app-secret
                      key: DB_USER
                - name: MONGODB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: app-secret
                      key: DB_PASSWORD
                - name: MONGODB_COLLECTION
                  value: Pic
              volumeMounts:
                - name: backup
                  mountPath: /backup
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
            - name: pic-tag-replace-table
              image: public.ecr.aws/docker/library/mongo:7.0.34-jammy@sha256:80bdab05c3cdc7c233438f70553960e86112e0fc9d46f0409ee03fc796bb24b7
              command:
                - bash
                - -c
                - |
                  mongoexport \
                  --uri="mongodb://$MONGODB_USER:$MONGODB_PASSWORD@db:27017/stella?authSource=admin" \
                  --collection=$MONGODB_COLLECTION \
                  --out /backup/${MONGODB_COLLECTION}.json
              env:
                - name: MONGODB_USER
                  valueFrom:
                    secretKeyRef:
                      name: app-secret
                      key: DB_USER
                - name: MONGODB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: app-secret
                      key: DB_PASSWORD
                - name: MONGODB_COLLECTION
                  value: PicTagReplaceTable
              volumeMounts:
                - name: backup
                  mountPath: /backup
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
          volumes:
            - name: backup
              hostPath:
                path: /mnt/local/stella-backup
                type: DirectoryOrCreate
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
  concurrencyPolicy: Forbid
