# v41 で logs.access から accessLog に移動し、キーは camelCase になった。
# https://doc.traefik.io/traefik/reference/install-configuration/observability/logs-and-accesslogs/
accessLog:
  enabled: true
  # https://doc.traefik.io/traefik/observe/logs-and-access-logs/#log-fields-customization
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep
      names:
        Authorization: drop
    names:
      StartUTC: drop
  format: json

autoscaling:
  enabled: false

deployment:
  minReadySeconds: 30
  replicas: 1

envFrom:
  - configMapRef:
      name: traefik-env

image:
  registry: public.ecr.aws/docker/library

ingressRoute:
  dashboard:
    enabled: false

# v41 で logs.general から log に移動した。
# https://doc.traefik.io/traefik/reference/install-configuration/observability/logs-and-accesslogs/
log:
  level: INFO

metrics:
  prometheus: null

ports:
  web:
    asDefault: true
    expose:
      default: true
    exposedPort: 30080

    forwardedHeaders:
      trustedIPs:
        - 10.2.0.0/16
        - fd11:eed0:a3e9::/64

    nodePort: 30080
    port: 30080

  websecure: null

providers:
  kubernetesCRD:
    allowCrossNamespace: true
    allowEmptyServices: true
    enabled: true
  kubernetesIngress:
    enabled: false

service:
  ipFamilyPolicy: PreferDualStack
  type: NodePort
