apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: app
          image: ghcr.io/slashnephy/watch-k8s-events:master@sha256:54f9049e929a28625b92ac314cdfc5b6f04caf01ec284d7f8f1fbcebed845856
          envFrom:
            - secretRef:
                name: app-secret
          securityContext:
            allowPrivilegeEscalation: false
      restartPolicy: Always
      serviceAccountName: watch-k8s-events
