apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n

images:
  # チャートの更新が遅いのでセルフアップデート
  - name: n8nio/n8n
    newTag: 2.17.2@sha256:4e5be628f9eb05e3fde3cd242c84f6000165c95d2048d5076fcc569421ada4f3

helmCharts:
  # https://github.com/8gears/n8n-helm-chart
  - name: n8n
    releaseName: n8n
    namespace: n8n
    version: 2.0.1
    repo: oci://8gears.container-registry.com/library
    includeCRDs: true
    valuesInline:
      main:
        config:
          db:
            postgresdb:
              database: n8n
              host: postgresql
              user: n8n
            type: postgresdb
          generic:
            timezone: Asia/Tokyo
          n8n:
            diagnostics_enabled: "false"
            host: n8n.starry.blue
            protocol: https
            proxy_hops: "1"
            version_notifications_enabled: "false"
        extraEnv:
          DB_POSTGRESDB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: password
          N8N_ENCRYPTION_KEY:
            valueFrom:
              secretKeyRef:
                name: n8n-secret
                key: encryption_key
          N8N_LICENSE_ACTIVATION_KEY:
            valueFrom:
              secretKeyRef:
                name: n8n-secret
                key: license_activation_key
        persistence:
          enabled: true
          existingClaim: n8n-data
          type: existing
      # TODO: worker を分離
      # worker:
      #   enabled: true
      #   replicaCount: 1
      # valkey:
      #   enabled: true
      #   auth:
      #     enabled: false
  - name: postgresql
    releaseName: postgresql
    version: 18.6.2
    repo: oci://registry-1.docker.io/bitnamicharts
    valuesInline:
      auth:
        database: n8n
        existingSecret: postgresql-secret
        username: n8n
      backup:
        cronjob:
          concurrencyPolicy: Forbid
          containerSecurityContext:
            runAsGroup: 1000
            runAsUser: 1000
          restartPolicy: Never
          # @hourly
          schedule: "20 * * * *"
          storage:
            existingClaim: n8n-postgresql-backup
          timeZone: Asia/Tokyo
        enabled: true
      global:
        imageRegistry: public.ecr.aws
        security:
          # imageRegistry を変更するために必要
          allowInsecureImages: true
      primary:
        extraEnvVars:
          - name: TZ
            value: Asia/Tokyo
        persistence:
          existingClaim: n8n-postgresql-data
        resourcesPreset: nano

resources:
  - ./resources/cronjob-cleanup-backup.yaml
  - ./resources/dns.yaml
  - ./resources/ingress.yaml
  - ./resources/secret.yaml
  - ./resources/service-lm-studio.yaml
  - ./resources/volume-backup.yaml
  - ./resources/volume-data.yaml
  - ./resources/volume-postgresql.yaml
