apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob

spec:
  schedule: "*/2 * * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
            - name: app
              image: ghcr.io/slashnephy/post-switchbot-metrics:master@sha256:64df17036bac5a30a8c4f49190ac7587090402ae2c2106481063966842772149
              env:
                - name: MACKEREL_SERVICE_NAME
                  value: SwitchBot
              envFrom:
                - secretRef:
                    name: app-secret
              securityContext:
                allowPrivilegeEscalation: false
          restartPolicy: Never
  concurrencyPolicy: Forbid
