apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob

spec:
  schedule: "*/2 * * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
            - name: app
              image: ghcr.io/slashnephy/post-switchbot-metrics:master@sha256:cd4ab14dc904b6bafd805b0a9e68aa0456df18526ece86abdefe33c715a81e79
              env:
                - name: MACKEREL_SERVICE_NAME
                  value: SwitchBot
              envFrom:
                - secretRef:
                    name: app-secret
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
  concurrencyPolicy: Forbid
