apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob

spec:
  schedule: "*/2 * * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
            - name: app
              image: ghcr.io/slashnephy/post-switchbot-metrics:master@sha256:d5c290e91ade7329d49c4b3f43cac3d2ce13d805423ea6f895eec521e1c7540e
              env:
                - name: MACKEREL_SERVICE_NAME
                  value: SwitchBot
              envFrom:
                - secretRef:
                    name: app-secret
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
  concurrencyPolicy: Forbid
