apiVersion: authentik.starry.blue/v1alpha1
kind: AuthentikApplication
metadata:
  name: home-assistant

spec:
  access:
    rules:
      - group:
          name: Admin
  adopt: IfMatch
  group: Personal
  icon: https://github.com/home-assistant.png
  name: Home Assistant
  provider:
    name: Home Assistant
    flows:
      authorization:
        slug: authorize
      invalidation:
        slug: default-provider-invalidation-flow
    proxy:
      accessTokenValidity: days=1
      forwardAuthSingle:
        externalHost: https://home.starry.blue
      interceptHeaderAuth: true
      outpost:
        name: authentik Embedded Outpost
      refreshTokenValidity: days=30
  slug: home-assistant
