# TODO: valuesInline に戻す
# https://github.com/actions/actions-runner-controller/issues/3819

controllerServiceAccount:
  name: arc-gha-rs-controller
  namespace: arc-systems
githubConfigSecret: runner-secret

githubConfigUrl: https://github.com/SlashNephy/nebula
maxRunners: 4

minRunners: 0
template:
  spec:
    containers:
      - name: runner
        command:
          - /home/runner/run.sh

        image: ghcr.io/slashnephy/actions-runner:latest@sha256:3db51966b6536780c23706cfc0ce5d829984066d321ba2054ea9971b79eab3c9
