# TODO: valuesInline に戻す
# https://github.com/actions/actions-runner-controller/issues/3819

controllerServiceAccount:
  name: arc-gha-rs-controller
  namespace: arc-systems
githubConfigSecret: runner-secret

githubConfigUrl: https://github.com/SlashNephy/nebula
maxRunners: 4

minRunners: 0
template:
  spec:
    containers:
      - name: runner
        command:
          - /home/runner/run.sh

        image: ghcr.io/slashnephy/actions-runner:latest@sha256:58936377e982f831ffd4435aeca64c7882259ea6124aa19993bba12f95e38517
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
