# TODO: valuesInline に戻す
# https://github.com/actions/actions-runner-controller/issues/3819

controllerServiceAccount:
  name: arc-gha-rs-controller
  namespace: arc-systems
githubConfigSecret: runner-secret

githubConfigUrl: https://github.com/SlashNephy/nebula
maxRunners: 4

minRunners: 0
template:
  spec:
    containers:
      - name: runner
        command:
          - /home/runner/run.sh

        image: ghcr.io/slashnephy/actions-runner:latest@sha256:e39c3cd34352c618809b876ee2f7c97fd2c88d0cfb534291b885f29429f14698
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
