apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mackerel-operator

helmCharts:
  - name: mackerel-operator
    releaseName: mackerel-operator
    namespace: mackerel-operator
    version: 0.1.1
    repo: https://slashnephy.github.io/mackerel-operator
    includeCRDs: true

resources:
  - ./resources/secret.yaml
