apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: server
          image: ghcr.io/immich-app/immich-server:v3.2.0@sha256:ae13784ffcfcce8f4178113eb6661602a1fd1912f3d539880b8ac0dd95fc8ac2
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          ports:
            - containerPort: 2283
          volumeMounts:
            - name: data
              mountPath: /data
            - name: media-nebula
              mountPath: /mnt/pool/nebula_media
              readOnly: true
          resources:
            limits:
              gpu.intel.com/i915: "1"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
        - name: machine-learning
          image: ghcr.io/immich-app/immich-machine-learning:v3.2.0-openvino@sha256:6387b84ab42da139191c3db686faead6555ab8cac6466d1d20be955735961b98
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          ports:
            - containerPort: 3003
          volumeMounts:
            - name: model-cache
              mountPath: /cache
            - name: tmp
              mountPath: /tmp
          resources:
            limits:
              gpu.intel.com/i915: "1"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: data
          hostPath:
            path: /mnt/local/immich/data
            type: DirectoryOrCreate
        - name: model-cache
          hostPath:
            path: /mnt/local/immich/model-cache
            type: DirectoryOrCreate
        - name: media-nebula
          hostPath:
            path: /mnt/pool/nebula_media
            type: Directory
        - name: tmp
          emptyDir: {}
      restartPolicy: Always
      securityContext:
        seccompProfile:
          type: RuntimeDefault
