apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: server
          image: ghcr.io/immich-app/immich-server:v2.6.3@sha256:0cc1f82953d9598eb9e9dd11cbde1f50fe54f9c46c4506b089e8ad7bfc9d1f0c
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          ports:
            - containerPort: 2283
          volumeMounts:
            - name: data
              mountPath: /data
            - name: media-nebula
              mountPath: /mnt/pool/nebula_media
              readOnly: true
          resources:
            limits:
              gpu.intel.com/i915: "1"
          securityContext:
            allowPrivilegeEscalation: false
        - name: machine-learning
          image: ghcr.io/immich-app/immich-machine-learning:v2.6.3-openvino@sha256:428b319762c5c0f39218162bd24cab38f48d369c580389e9897c8ab92807cf7a
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          ports:
            - containerPort: 3003
          volumeMounts:
            - name: model-cache
              mountPath: /cache
            - name: dev-bus-usb
              mountPath: /dev/bus/usb
          resources:
            limits:
              gpu.intel.com/i915: "1"
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: data
          hostPath:
            path: /mnt/local/immich/data
            type: DirectoryOrCreate
        - name: model-cache
          hostPath:
            path: /mnt/local/immich/model-cache
            type: DirectoryOrCreate
        - name: dev-bus-usb
          hostPath:
            path: /dev/bus/usb
            type: Directory
        - name: media-nebula
          hostPath:
            path: /mnt/pool/nebula_media
            type: Directory
      restartPolicy: Always
