apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup

spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: pg-dump
              image: public.ecr.aws/docker/library/postgres:17.0-bookworm@sha256:4ec37d2a07a0067f176fdcc9d4bb633a5724d2cc4f892c7a2046d054bb6939e5
              command:
                - bash
                - -c
                - |
                  pg_dump \
                    -f /backup/nebula.sql \
                    --if-exists \
                    --clean \
                    --column-inserts \
                    "$DATABASE_DSN"
              env:
                - name: DATABASE_DSN
                  valueFrom:
                    secretKeyRef:
                      name: server-secrets
                      key: DATABASE_DSN
              volumeMounts:
                - name: backup
                  mountPath: /backup
              securityContext:
                allowPrivilegeEscalation: false
          volumes:
            - name: backup
              hostPath:
                path: /opt/k8s-volumes/nebula/backup
                type: DirectoryOrCreate
          restartPolicy: Never
  concurrencyPolicy: Forbid
