apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-cleanup-backup

spec:
  schedule: "0 * * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: app
              image: public.ecr.aws/debian/debian:stable-slim@sha256:6481949aa8a8902231c22efa43b21d9e4a71af48b894b7b453831492ea169525
              workingDir: /backup
              command:
                - bash
                - -c
                - ls -1r pg_dumpall-*.pgdump | tail -n +$((KEEP_COUNT + 1)) | xargs -r rm -v
              env:
                - name: KEEP_COUNT
                  value: "3"
              volumeMounts:
                - name: backup
                  mountPath: /backup
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
                runAsGroup: 1001
                runAsNonRoot: true
                runAsUser: 1001
          volumes:
            - name: backup
              hostPath:
                path: /mnt/local/nebula/postgresql-backup
                type: Directory
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
  concurrencyPolicy: Forbid
