apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg

spec:
  replicas: 2
  selector:
    matchLabels:
      app: ffmpeg
  template:
    metadata:
      labels:
        app: ffmpeg
    spec:
      containers:
        - name: ffmpeg
          image: ghcr.io/slashnephy/nebula-ffmpeg:main@sha256:9f6913d3d8b14e9cc153cbdea1b22e7a9bdb82ade991eb6b311ccf14b3180aee
          ports:
            - name: http
              containerPort: 8087
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: tmp
          emptyDir: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-io-credentials
      securityContext:
        seccompProfile:
          type: RuntimeDefault
