apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker

spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/slashnephy/nebula-worker:main@sha256:5dc7c9909bd2abb8c66a812d6a6318adeeef8d56b008bee9403d4d13e46c1a47
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          volumeMounts:
            - name: media
              mountPath: /app/media
            - name: thumbnails
              mountPath: /app/thumbnails
            - name: avatars
              mountPath: /app/avatars
            - name: tmp
              mountPath: /tmp
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: media
          hostPath:
            path: /mnt/local/nebula/media
            type: Directory
        - name: thumbnails
          hostPath:
            path: /mnt/local/nebula/thumbnails
            type: Directory
        - name: avatars
          hostPath:
            path: /mnt/local/nebula/avatars
            type: Directory
        - name: tmp
          emptyDir: {}
      restartPolicy: Always
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: ghcr-io-credentials
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 90
