apiVersion: apps/v1
kind: Deployment
metadata:
  name: xctid

spec:
  replicas: 2
  selector:
    matchLabels:
      app: xctid
  template:
    metadata:
      labels:
        app: xctid
    spec:
      containers:
        - name: xctid
          image: ghcr.io/slashnephy/nebula-xctid:main@sha256:be8687b7eeb7a1bd87459c4df6e1aa2f44b0430c5bbf06495961a5187d10d0de
          envFrom:
            - secretRef:
                name: xctid-secrets
          ports:
            - name: http
              containerPort: 8084
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-io-credentials
      securityContext:
        seccompProfile:
          type: RuntimeDefault
