apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: server
          image: ghcr.io/slashnephy/nebula-server:master@sha256:42b452db8dc9d648b070a5b6f87d34077d89eb51e62f756433e1e5e57c3c5d3a
          env:
            - name: SERVER_ORIGIN
              value: https://nebula-api.starry.blue
          envFrom:
            - secretRef:
                name: server-secrets
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: media
              mountPath: /backend/media
            - name: avatars
              mountPath: /backend/avatars
            - name: content
              mountPath: /backend/content
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          securityContext:
            allowPrivilegeEscalation: false
        - name: worker
          image: ghcr.io/slashnephy/nebula-server:master@sha256:42b452db8dc9d648b070a5b6f87d34077d89eb51e62f756433e1e5e57c3c5d3a
          command:
            - /backend/worker
          env:
            - name: SERVER_ORIGIN
              value: https://nebula-api.starry.blue
          envFrom:
            - secretRef:
                name: server-secrets
          volumeMounts:
            - name: media
              mountPath: /backend/media
            - name: avatars
              mountPath: /backend/avatars
            - name: content
              mountPath: /backend/content
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: media
          hostPath:
            path: /mnt/pool/nebula_media
            type: DirectoryOrCreate
        - name: avatars
          hostPath:
            path: /mnt/local/nebula/avatars
            type: DirectoryOrCreate
        - name: content
          hostPath:
            path: /mnt/pool/nebula_media
            type: DirectoryOrCreate
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-io-credentials
