apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker

spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/slashnephy/nebula-worker:main@sha256:5ae697df8b6316902d146b9caa3f6bde5ef844eff1a95eb928400f015c7d2dc6
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          volumeMounts:
            - name: media
              mountPath: /app/media
            - name: avatars
              mountPath: /app/avatars
            - name: media
              mountPath: /app/content
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: media
          hostPath:
            path: /mnt/pool/nebula_media
            type: DirectoryOrCreate
        - name: avatars
          hostPath:
            path: /mnt/local/nebula/avatars
            type: DirectoryOrCreate
      restartPolicy: Always
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: ghcr-io-credentials
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 90
