apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml
  template:
    metadata:
      labels:
        app: ml
    spec:
      containers:
        - name: ml
          image: ghcr.io/slashnephy/nebula-ml:main@sha256:0ff94ba1f6e703b4d00a9596046a7ded5f872efb659826e5c08c47e570177cf0
          env:
            - name: DEVICE
              value: openvino
            - name: MODEL_CACHE_DIR
              value: /cache
            - name: MAX_MEMORY_MB
              value: "2048"
          ports:
            - name: http
              containerPort: 8083
          volumeMounts:
            - name: model-cache
              mountPath: /cache
            - name: dev-bus-usb
              mountPath: /dev/bus/usb
            - name: tmp
              mountPath: /tmp
          resources:
            limits:
              gpu.intel.com/i915: "1"
          livenessProbe:
            httpGet:
              path: /health
              port: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            # TODO: あとで対応
            readOnlyRootFilesystem: false
      volumes:
        - name: model-cache
          hostPath:
            path: /mnt/local/nebula/ml-model-cache
            type: DirectoryOrCreate
        - name: dev-bus-usb
          hostPath:
            path: /dev/bus/usb
            type: Directory
        - name: tmp
          emptyDir: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-io-credentials
      securityContext:
        seccompProfile:
          type: RuntimeDefault
