apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: server
          image: ghcr.io/slashnephy/nebula-backend:2026.3.29@sha256:a260fc63d5b38cf72fc1e65a6932556439e27d87ba4ff60367c88f09aebd4941
          env:
            - name: SERVER_ORIGIN
              value: https://nebula-api.starry.blue
          envFrom:
            - secretRef:
                name: backend-secrets
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: media
              mountPath: /backend/media
            - name: avatars
              mountPath: /backend/avatars
            - name: content
              mountPath: /backend/content
          livenessProbe:
            httpGet:
              path: /health
              port: http
          securityContext:
            allowPrivilegeEscalation: false
        - name: worker
          image: ghcr.io/slashnephy/nebula-backend:2026.3.29@sha256:a260fc63d5b38cf72fc1e65a6932556439e27d87ba4ff60367c88f09aebd4941
          command:
            - /backend/worker
          env:
            - name: SERVER_ORIGIN
              value: https://nebula-api.starry.blue
          envFrom:
            - secretRef:
                name: backend-secrets
          volumeMounts:
            - name: media
              mountPath: /backend/media
            - name: avatars
              mountPath: /backend/avatars
            - name: content
              mountPath: /backend/content
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: media
          hostPath:
            path: /mnt/pool/nebula_media
            type: DirectoryOrCreate
        - name: avatars
          hostPath:
            path: /mnt/local/nebula/avatars
            type: DirectoryOrCreate
        - name: content
          hostPath:
            path: /mnt/pool/nebula_media
            type: DirectoryOrCreate
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-io-credentials
