apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg

spec:
  replicas: 2
  selector:
    matchLabels:
      app: ffmpeg
  template:
    metadata:
      labels:
        app: ffmpeg
    spec:
      containers:
        - name: ffmpeg
          image: ghcr.io/slashnephy/nebula-ffmpeg:main@sha256:8000c5b67e9a4f9833110aa7599c3f0f09decef0a3140ac77c9564207fb40f5c
          ports:
            - name: http
              containerPort: 8087
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: tmp
          emptyDir: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-io-credentials
      securityContext:
        seccompProfile:
          type: RuntimeDefault
