apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytdlp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: ytdlp
  template:
    metadata:
      labels:
        app: ytdlp
    spec:
      containers:
        - name: ytdlp
          image: ghcr.io/slashnephy/nebula-ytdlp:main@sha256:674e6e871571fb2e57ccd5c62900e2916cbc11e7c76e0f3037ee80dc72efc3d8
          envFrom:
            - secretRef:
                name: ytdlp-secrets
          ports:
            - name: http
              containerPort: 8086
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: tmp
          emptyDir: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-io-credentials
      securityContext:
        seccompProfile:
          type: RuntimeDefault
