apiVersion: apps/v1
kind: Deployment
metadata:
  name: xctid

spec:
  replicas: 2
  selector:
    matchLabels:
      app: xctid
  template:
    metadata:
      labels:
        app: xctid
    spec:
      containers:
        - name: xctid
          image: ghcr.io/slashnephy/nebula-xctid:main@sha256:65ed09e8cc329e31746410a8e74a2349864c75619212ca94d254c4f4771c0183
          ports:
            - name: http
              containerPort: 8084
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-io-credentials
      securityContext:
        seccompProfile:
          type: RuntimeDefault
