apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytdlp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: ytdlp
  template:
    metadata:
      labels:
        app: ytdlp
    spec:
      containers:
        - name: ytdlp
          image: ghcr.io/slashnephy/nebula-ytdlp:main@sha256:00950cea058e4d1c8beb842da80b41b0f3a60c25dedb7191cffda08c2628c9e6
          envFrom:
            - secretRef:
                name: ytdlp-secrets
          ports:
            - name: http
              containerPort: 8086
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: tmp
          emptyDir: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-io-credentials
      securityContext:
        seccompProfile:
          type: RuntimeDefault
