apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/slashnephy/nebula-frontend:master@sha256:2b25629f6dd3ade7e4cb247dbb0601697a95a39ffc2fcff6bb40e956993375f7
          env:
            - name: API_ORIGIN
              value: http://backend:8080
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: http
          securityContext:
            allowPrivilegeEscalation: false
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-io-credentials
