apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram

spec:
  replicas: 2
  selector:
    matchLabels:
      app: instagram
  template:
    metadata:
      labels:
        app: instagram
    spec:
      containers:
        - name: instagram
          image: ghcr.io/slashnephy/nebula-instagram:main@sha256:9cde03ff46a63aa0b0be90c11239ab3f8d51b22509627ab233730d3c83276c87
          envFrom:
            - secretRef:
                name: instagram-secrets
          ports:
            - name: http
              containerPort: 8085
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-io-credentials
      securityContext:
        seccompProfile:
          type: RuntimeDefault
