apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: server
          image: ghcr.io/slashnephy/nebula-backend:main@sha256:2fe4df85e15d6eaf1d900a93fb7a383170deb8ae3d0d6aa85a6e722a80994bec
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: media
              mountPath: /backend/media
            - name: avatars
              mountPath: /backend/avatars
            - name: content
              mountPath: /backend/content
          livenessProbe:
            httpGet:
              path: /health
              port: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
        - name: worker
          image: ghcr.io/slashnephy/nebula-backend:main@sha256:2fe4df85e15d6eaf1d900a93fb7a383170deb8ae3d0d6aa85a6e722a80994bec
          command:
            - /backend/worker
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          volumeMounts:
            - name: media
              mountPath: /backend/media
            - name: avatars
              mountPath: /backend/avatars
            - name: content
              mountPath: /backend/content
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: media
          hostPath:
            path: /mnt/pool/nebula_media
            type: DirectoryOrCreate
        - name: avatars
          hostPath:
            path: /mnt/local/nebula/avatars
            type: DirectoryOrCreate
        - name: content
          hostPath:
            path: /mnt/pool/nebula_media
            type: DirectoryOrCreate
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-io-credentials
      securityContext:
        seccompProfile:
          type: RuntimeDefault
