apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram

spec:
  replicas: 2
  selector:
    matchLabels:
      app: instagram
  template:
    metadata:
      labels:
        app: instagram
    spec:
      containers:
        - name: instagram
          image: ghcr.io/slashnephy/nebula-instagram:main@sha256:540568de56ef907332c4359af64932ab0e51b93f51855bd6562ef05c1075a7d8
          ports:
            - name: http
              containerPort: 8085
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-io-credentials
      securityContext:
        seccompProfile:
          type: RuntimeDefault
