apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: server
          image: ghcr.io/slashnephy/nebula-backend:main@sha256:a209345d4f6ac422b73c6e74a4b5afe831507c11240a00e84ea3d27f039b5c36
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: media
              mountPath: /app/media
            - name: avatars
              mountPath: /app/avatars
            - name: content
              mountPath: /app/content
          livenessProbe:
            httpGet:
              path: /health
              port: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
        - name: worker
          image: ghcr.io/slashnephy/nebula-worker:main@sha256:61f177a71ec450d638c12b046149043d38915144c63acb53bfe5106e9206164a
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          volumeMounts:
            - name: media
              mountPath: /app/media
            - name: avatars
              mountPath: /app/avatars
            - name: content
              mountPath: /app/content
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: media
          hostPath:
            path: /mnt/pool/nebula_media
            type: DirectoryOrCreate
        - name: avatars
          hostPath:
            path: /mnt/local/nebula/avatars
            type: DirectoryOrCreate
        - name: content
          hostPath:
            path: /mnt/pool/nebula_media
            type: DirectoryOrCreate
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-io-credentials
      securityContext:
        seccompProfile:
          type: RuntimeDefault
