apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker

spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/slashnephy/nebula-worker:main@sha256:5a517289bd666723761e05aa65a3f19f9b3b154c46d3569949d46b45f5f47a57
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          volumeMounts:
            - name: avatars
              mountPath: /app/avatars
            - name: media
              mountPath: /app/content
            - name: tmp
              mountPath: /tmp
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: media
          hostPath:
            path: /mnt/pool/nebula_media
            type: DirectoryOrCreate
        - name: avatars
          hostPath:
            path: /mnt/local/nebula/avatars
            type: DirectoryOrCreate
        - name: tmp
          emptyDir: {}
      restartPolicy: Always
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: ghcr-io-credentials
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 90
