apiVersion: apps/v1
kind: Deployment
metadata:
  name: river-ui

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: river-ui
  template:
    metadata:
      labels:
        app: river-ui
    spec:
      containers:
        - name: app
          image: ghcr.io/riverqueue/riverui:0.16.0@sha256:9c272ce4388a6a0ed18553d9b645b46f1b4a0f5b5b23bf93b1bf5ab82d8bb998
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DATABASE_DSN
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      restartPolicy: Always
      securityContext:
        seccompProfile:
          type: RuntimeDefault
