apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml

spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml
  template:
    metadata:
      labels:
        app: ml
    spec:
      containers:
        - name: ml
          image: ghcr.io/slashnephy/nebula-ml:main@sha256:62a5a6ce98d15e7ec41cd2ed4fd3c617add21e4907a32d2683ab7f00b536e80e
          env:
            - name: DEVICE
              value: openvino
            - name: MODEL_CACHE_DIR
              value: /cache
            - name: MAX_MEMORY_MB
              value: "4096"
          envFrom:
            - secretRef:
                name: ml-secrets
          ports:
            - name: http
              containerPort: 8083
          volumeMounts:
            - name: model-cache
              mountPath: /cache
            - name: tmp
              mountPath: /tmp
          resources:
            limits:
              gpu.intel.com/i915: "1"
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: model-cache
          hostPath:
            path: /mnt/local/nebula/ml-model-cache
            type: DirectoryOrCreate
        - name: tmp
          emptyDir: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-io-credentials
      securityContext:
        seccompProfile:
          type: RuntimeDefault
