apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: backend-secrets

spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/ht67ujhts3buxpq5fjyan6f4l4

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: ml-secrets

spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/qtwzh3vi6xgqunjezn3p4ltdt4

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: xctid-secrets

spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/mieycq4z76gut626wxb3juhfze

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: instagram-secrets

spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/o4vskjpaznzhz4uxd3frhcnk3a

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: ytdlp-secrets

spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/jlus6chkrej2ct7equkelw4aby

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgresql-secret

spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/h52gs5irccfoaalph6fuahiuni

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: backup-database-secrets

spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/i2iaxmxwc2vdnkwt4hsvodftc4

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: redis-secret

spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/5y5jgpno6nt24tgapqmuyvlheu
