apiVersion: v1
kind: Service
metadata:
  name: backend

spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: frontend

spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: river-ui

spec:
  selector:
    app: river-ui
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
