apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: starry-blue-certificate

spec:
  commonName: starry.blue
  dnsNames:
    - starry.blue
    - "*.starry.blue"
    - "*.gateway.starry.blue"
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 384
  secretName: starry-blue-certificate-secret
