apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: gateway

spec:
  alpnProtocols:
    # https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids
    - h3
    - h2
    - h2c
    - http/1.1
    - dot # DNS over TLS
  maxVersion: VersionTLS13
  minVersion: VersionTLS13
  sniStrict: true
