 
 

configs:
  default:
    globals:
      - general
      - logging
      - performance
      - security
      - follow_symlinks
      - no_printing

    shares:
      - pool
globals:
  follow_symlinks:
    options:
      follow symlinks: "yes"
      unix extensions: "no"
      wide links: "yes"
  general:
    options:
      server role: standalone server
      server string: Samba Server
      vfs objects: catia fruit streams_xattr full_audit
      workgroup: MYGROUP
  logging:
    options:
      full_audit:facility: local1
      full_audit:failure: connect
      full_audit:prefix: "%U|%m|%I"
      full_audit:success: connect disconnect read pread
      log file: /dev/stdout
      log level: "2"
  no_printing:
    options:
      disable spoolss: "yes"
      load printers: "no"
      printcap name: /dev/null
      printing: bsd
  performance:
    options:
      aio read size: "16384"
      aio write size: "16384"
      deadtime: "15"
      min receivefile size: "16384"
      server multi channel support: "yes"
      socket options: IPTOS_THROUGHPUT SO_KEEPALIVE
      strict locking: "no"
      use sendfile: "yes"
  security:
    options:
      min protocol: SMB3
      nt pipe support: "no"
      restrict anonymous: "1"
# https://github.com/samba-in-kubernetes/sambacc/blob/master/docs/configuration.md
samba-container-config: v0
shares:
  pool:
    options:
      browseable: "yes"
      create mask: "0664"
      directory mask: "0775"

      guest ok: "no"
      path: /mnt/pool
      printable: "no"
      public: "no"
      valid users: spica
      writable: "yes"

