apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob

spec:
  schedule: "0 9 * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: gh
              image: public.ecr.aws/docker/library/alpine:3.24.2@sha256:31b6477333eb8257db9e5d7c3a7264fd0467928756f0bbcc27d35bea5d28cdbd
              command:
                - ash
                - -c
                - |
                  apk add github-cli
                  gh api \
                    --method POST \
                    -H "Accept: application/vnd.github.v3+json" \
                    /repos/SlashNephy/TVTest-builder/releases \
                    -f tag_name="$(date -Idate)"
              envFrom:
                - secretRef:
                    name: github-secret
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
