apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob

spec:
  schedule: "0 9 * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: gh
              image: public.ecr.aws/docker/library/alpine:3.23.4@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
              command:
                - ash
                - -c
                - |
                  apk add github-cli
                  gh api \
                    --method POST \
                    -H "Accept: application/vnd.github.v3+json" \
                    /repos/SlashNephy/TVTest-builder/releases \
                    -f tag_name="$(date -Idate)"
              envFrom:
                - secretRef:
                    name: github-secret
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
  concurrencyPolicy: Forbid
