apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "4533"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: default
    spec:
      containers:
        - name: app
          image: deluan/navidrome:0.61.1@sha256:1e1660054a856cc09f227d6929252e45a519fdb16004b464dd637f7294ca3ec1
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 4533
          volumeMounts:
            - name: data
              mountPath: /data
            - name: music
              mountPath: /music
              readOnly: true
            - name: backup
              mountPath: /backup
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsUser: 1000
      volumes:
        - name: data
          hostPath:
            path: /mnt/local/navidrome/data
            type: DirectoryOrCreate
        - name: music
          hostPath:
            path: /mnt/pool/music
            type: DirectoryOrCreate
        - name: backup
          hostPath:
            path: /mnt/local/navidrome/backup
            type: DirectoryOrCreate
      restartPolicy: Always
      securityContext:
        seccompProfile:
          type: RuntimeDefault
