apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "4533"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: default
    spec:
      containers:
        - name: app
          image: deluan/navidrome:0.63.2@sha256:9012939114fbb1bb641b81cf96dec5ded15f0aafefe8d47a511d7cb919658e40
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 4533
          volumeMounts:
            - name: data
              mountPath: /data
            - name: music
              mountPath: /music
              readOnly: true
            - name: backup
              mountPath: /backup
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 1000
            runAsUser: 1000
      volumes:
        - name: data
          hostPath:
            path: /mnt/local/navidrome/data
            type: DirectoryOrCreate
        - name: music
          hostPath:
            path: /mnt/pool/music
            type: DirectoryOrCreate
        - name: backup
          hostPath:
            path: /mnt/local/navidrome/backup
            type: DirectoryOrCreate
      restartPolicy: Always
      securityContext:
        seccompProfile:
          type: RuntimeDefault
