apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: dns

spec:
  endpoints:
    - dnsName: navidrome.starry.blue
      recordTTL: 1
      recordType: CNAME
      targets:
        - gateway.starry.blue
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"
    - dnsName: navidrome.gateway.starry.blue
      recordTTL: 300
      recordType: CNAME
      targets:
        - gateway.starry.blue
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
