apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: anythingllm

helmCharts:
  # https://github.com/Mintplex-Labs/helm-charts
  - name: anythingllm
    releaseName: anythingllm
    namespace: anythingllm
    version: 1.0.0
    repo: https://mintplex-labs.github.io/helm-charts
    valuesInline:
      config:
        DISABLE_TELEMETRY: "true"
        GID: "1000"
        NODE_ENV: production
        STORAGE_DIR: /app/server/storage
        TZ: Asia/Tokyo
        UID: "1000"
      ingress:
        enabled: false
      persistentVolume:
        existingClaim: anythingllm-data

resources:
  - ./resources/volume.yaml
  - ./resources/ingress.yaml
  - ./resources/dns.yaml

patches:
  # /spec/template/spec/strategy は存在しないので削除する (out-of-sync 状態が継続してしまうため)
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: anythingllm
    patch: |-
      - op: remove
        path: /spec/template/spec/strategy
