apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob

spec:
  schedule: "*/5 * * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: app
              image: ghcr.io/slashnephy/anilist-synchronizer:master@sha256:f1e59e86bbe37ee1c5cd1473cf54d4f22765c014a19646a476460747f1533b6d
              env:
                - name: ANILIST_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: app-secret
                      key: anilist-client-id
                - name: ANILIST_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: app-secret
                      key: anilist-client-secret
                - name: TOKEN_DIRECTORY
                  value: /app/token
              volumeMounts:
                - name: token
                  mountPath: /app/token
              securityContext:
                allowPrivilegeEscalation: false
          volumes:
            - name: token
              hostPath:
                path: /mnt/local/anilist-synchronizer/token
                type: DirectoryOrCreate
          restartPolicy: Never
  concurrencyPolicy: Forbid
