apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: public.ecr.aws/docker/library/archlinux:base@sha256:63c7b061c0c001cb7ce4f8d11b63d351c23e7f97121bc5c8bd5d9f431e615d7d
          args:
            - sleep
            - infinity
          env:
            - name: TZ
              value: Asia/Tokyo
          volumeMounts:
            - name: data
              mountPath: /data
              mountPropagation: HostToContainer
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
      restartPolicy: Always
      securityContext:
        seccompProfile:
          type: RuntimeDefault
