apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: public.ecr.aws/docker/library/archlinux:base@sha256:bb1e5dd58eb79755e736ac530292074f4408572c0fbc4306cd62b431fdf356f0
          args:
            - sleep
            - infinity
          env:
            - name: TZ
              value: Asia/Tokyo
          volumeMounts:
            - name: data
              mountPath: /data
              mountPropagation: HostToContainer
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
      restartPolicy: Always
