apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: public.ecr.aws/docker/library/archlinux:base@sha256:a9a1e6db522cf5f8018c920d035e2bfbf8e39c485ee737ce0388990898f2f042
          args:
            - sleep
            - infinity
          env:
            - name: TZ
              value: Asia/Tokyo
          volumeMounts:
            - name: data
              mountPath: /data
              mountPropagation: HostToContainer
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
      restartPolicy: Always
      securityContext:
        seccompProfile:
          type: RuntimeDefault
