apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup

spec:
  schedule: "10 * * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: backup
              image: ghcr.io/slashnephy/epgstation-custom-hwaccel:master@sha256:b062ba4138d2183ff16c6c11e62443b31013c392e90061c4b5f74de7b5b3b1f4
              command:
                - node
                - dist/DBTools.js
                - -m
                - backup
                - -o
                - /backup/epgstation.json
              volumeMounts:
                - name: backup
                  mountPath: /backup
                - name: data
                  mountPath: /app/data
                  readOnly: true
                - name: config
                  mountPath: /app/config
                  readOnly: true
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
          volumes:
            - name: backup
              hostPath:
                path: /mnt/local/epgstation/backup
                type: DirectoryOrCreate
            - name: data
              hostPath:
                path: /mnt/local/epgstation/data
                type: DirectoryOrCreate
            - name: config
              hostPath:
                path: /mnt/local/epgstation/config
                type: Directory
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
  concurrencyPolicy: Forbid
