apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: headlessx-secret

spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/e2h2yjnqz6lduqtuakes7irh5q

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgresql-secret

spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/3mgrqojmz2e6ziqj7jag6dcpoe
