apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headlessx-postgresql-data
spec:
  selector:
    matchLabels:
      name: headlessx-postgresql-data
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: headlessx-postgresql-data
  labels:
    name: headlessx-postgresql-data

spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 4Gi
  local:
    path: /mnt/local/headlessx/postgresql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - lily
  persistentVolumeReclaimPolicy: Retain
