apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw

resources:
  - ./resources/dns.yaml
  - ./resources/ingress.yaml
  - ./resources/instance.yaml
  - ./resources/secret.yaml
  - ./resources/volume.yaml
