apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob

spec:
  schedule: "30 * * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: app
              image: ghcr.io/slashnephy/annict2anilist:master@sha256:518b2ef9d62d900e6550219da0e72a2f3860718f87a67f7aaecb977b722a3c01
              env:
                - name: TOKEN_DIRECTORY
                  value: /app/token
                - name: LOG_LEVEL
                  value: DEBUG
              envFrom:
                - secretRef:
                    name: app-secret
              volumeMounts:
                - name: token
                  mountPath: /app/token
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
          volumes:
            - name: token
              hostPath:
                path: /mnt/local/annict2anilist/token
                type: DirectoryOrCreate
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
  concurrencyPolicy: Forbid
