apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob

spec:
  schedule: "30 * * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: app
              image: ghcr.io/slashnephy/annict2anilist:master@sha256:fb26ac0a3b6b7ec6446256b83207c1fda8ea85dd46280bd83854440b27ce2bdc
              env:
                - name: TOKEN_DIRECTORY
                  value: /app/token
                - name: LOG_LEVEL
                  value: DEBUG
              envFrom:
                - secretRef:
                    name: app-secret
              volumeMounts:
                - name: token
                  mountPath: /app/token
              securityContext:
                allowPrivilegeEscalation: false
          volumes:
            - name: token
              hostPath:
                path: /mnt/local/annict2anilist/token
                type: DirectoryOrCreate
          restartPolicy: Never
  concurrencyPolicy: Forbid
