apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob

spec:
  schedule: "30 * * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: app
              image: ghcr.io/slashnephy/annict2anilist:master@sha256:5bf5c2c3a78f34bb8441202e32ae3d81269d1e2968aa4c3e598e7ae7825232a2
              env:
                - name: TOKEN_DIRECTORY
                  value: /app/token
                - name: LOG_LEVEL
                  value: DEBUG
              envFrom:
                - secretRef:
                    name: app-secret
              volumeMounts:
                - name: token
                  mountPath: /app/token
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
          volumes:
            - name: token
              hostPath:
                path: /mnt/local/annict2anilist/token
                type: DirectoryOrCreate
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
  concurrencyPolicy: Forbid
