apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: app
          image: timothyjmiller/cloudflare-ddns:latest@sha256:1e2346dd943b639cb0ce77e8b12603484e45ee20449f5974430de64054a2985b
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: config
              mountPath: /config.json
              readOnly: true
              subPath: config.json
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: config
          secret:
            secretName: config
      restartPolicy: Always
