apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: app
          image: timothyjmiller/cloudflare-ddns:latest@sha256:db4a4277002cb3f43d39797997dce78ae4cc56f3739100d3ead1783146b5a049
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: config
              mountPath: /config.json
              readOnly: true
              subPath: config.json
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: config
          secret:
            secretName: config
      restartPolicy: Always
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
