apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: app
          image: ghcr.io/tsukumijima/konomitv:latest@sha256:6e4dda3d08971b79b016e061f747523129f8ab65e3268b3b603a78146ebaa1a7
          volumeMounts:
            - name: config
              mountPath: /code/config.yaml
              readOnly: true
              subPath: config.yaml
            - name: data
              mountPath: /code/server/data
          resources:
            limits:
              gpu.intel.com/i915: "1"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: config
          configMap:
            name: app-config
        - name: data
          emptyDir: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-io-credentials
      securityContext:
        seccompProfile:
          type: RuntimeDefault
