apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: app
          image: ghcr.io/tsukumijima/konomitv:latest@sha256:413bcc7a4f6d6891542530545d6c949b98a613ab49f2882c5d9041570f1c0f9a
          volumeMounts:
            - name: config
              mountPath: /code/config.yaml
              readOnly: true
              subPath: config.yaml
            - name: data
              mountPath: /code/server/data
          resources:
            limits:
              gpu.intel.com/i915: "1"
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: config
          configMap:
            name: app-config
        - name: data
          emptyDir: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-io-credentials
