apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      annotations:
        fluentbit.io/exclude: "true"
      labels:
        app: default
    spec:
      containers:
        - name: server
          image: ghcr.io/slashnephy/discord-broadcaster:master@sha256:23a9c71f20816f93db53d3a465031d23657d2c2fa3800af4ab0be2edb79935de
          env:
            - name: TZ
              value: Asia/Tokyo
          envFrom:
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
          securityContext:
            allowPrivilegeEscalation: false
        - name: redis
          image: public.ecr.aws/docker/library/redis:7.4.1-bookworm@sha256:d941b1988d3d75bf1a3d5c2b78a75806f59627a7a22db681a65f33e81f3f794d
          ports:
            - containerPort: 6379
          securityContext:
            allowPrivilegeEscalation: false
      restartPolicy: Always
