apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant

helmCharts:
  # https://github.com/pajikos/home-assistant-helm-chart
  - name: home-assistant
    releaseName: home-assistant
    namespace: home-assistant
    version: 0.3.49
    repo: http://pajikos.github.io/home-assistant-helm-chart/
    includeCRDs: true
    valuesInline:
      controller:
        type: Deployment
      deploymentStrategy: Recreate
      env:
        - name: TZ
          value: Asia/Tokyo
      persistence:
        enabled: true
        existingClaim: home-assistant-config

resources:
  - ./resources/dns.yaml
  - ./resources/ingress.yaml
  - ./resources/volume.yaml
