apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: epgstation

resources:
  - ./../../common/registry-ghcr-io/lily
  - ./resources/authentik.yaml
  - ./resources/configmap-mariadb.yaml
  - ./resources/cronjob-backup.yaml
  - ./resources/cronjob-db-maintenance.yaml
  - ./resources/cronjob-restart.yaml
  - ./resources/deployment.yaml
  - ./resources/dns.yaml
  - ./resources/ingress.yaml
  - ./resources/namespace.yaml
  - ./resources/secret.yaml
  - ./resources/service-mariadb.yaml
  - ./resources/service.yaml
  - ./resources/serviceaccount-mariadb.yaml
  - ./resources/statefulset-mariadb.yaml
  - ./resources/volume.yaml
