apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ghcr.io/justarchinet/archisteamfarm:6.3.4.2@sha256:7201b753f03e824fe4d9bdd336a4c6d951c545e230b623d2f745de72c9f55a46
          env:
            - name: TZ
              value: Asia/Tokyo
          envFrom:
            - secretRef:
                name: secret
          ports:
            - containerPort: 1242
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: plugins
              mountPath: /asf/plugins/external
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 1000
            runAsUser: 1000
      volumes:
        - name: config
          hostPath:
            path: /mnt/local/archi-steam-farm/config
            type: Directory
        - name: plugins
          hostPath:
            path: /mnt/local/archi-steam-farm/plugins
            type: Directory
      restartPolicy: Always
      hostname: archi-steam-farm
