apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      annotations:
        fluentbit.io/exclude: "true"
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ghcr.io/justarchinet/archisteamfarm:6.0.4.4@sha256:a00fe7a34ef9a472485da95ed93cd802796137d1c7d4e1509c00d5bc6990d1ad
          env:
            - name: TZ
              value: Asia/Tokyo
          ports:
            - containerPort: 1242
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: plugins
              mountPath: /asf/plugins/external
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: config
          hostPath:
            path: /mnt/pool/volumes/archi-steam-farm/config
            type: Directory
        - name: plugins
          hostPath:
            path: /mnt/pool/volumes/archi-steam-farm/plugins
            type: Directory
      restartPolicy: Always
