apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ghcr.io/justarchinet/archisteamfarm:6.3.5.0@sha256:eec617d8e7b4b2d1abc1e5950c0861629433f7702e7a85482e12fd17262469fb
          env:
            - name: TZ
              value: Asia/Tokyo
          envFrom:
            - secretRef:
                name: secret
          ports:
            - containerPort: 1242
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: plugins
              mountPath: /asf/plugins/external
              readOnly: true
            - name: tmp
              mountPath: /tmp
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsUser: 1000
      volumes:
        - name: config
          hostPath:
            path: /mnt/local/archi-steam-farm/config
            type: Directory
        - name: plugins
          hostPath:
            path: /mnt/local/archi-steam-farm/plugins
            type: Directory
        - name: tmp
          emptyDir: {}
      restartPolicy: Always
      hostname: archi-steam-farm
      securityContext:
        seccompProfile:
          type: RuntimeDefault
