apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mirakurun

resources:
  - ./../../../common/registry-ghcr-io/bbc
  - ./resources/deployment.yaml
  - ./resources/ingress.yaml
  - ./resources/namespace.yaml
  - ./resources/secret.yaml
  - ./resources/service.yaml
