apiVersion: openclaw.rocks/v1alpha1
kind: OpenClawInstance
metadata:
  name: agent

spec:
  image:
    repository: ghcr.io/openclaw/openclaw
    tag: 2026.3.2
    digest: sha256:6ce0b122e8675b0c14b2d352dff928273bd17c7b2148e69e13453b9ddffbf7cf
  config:
    mergeMode: merge
    raw:
      gateway:
        trustedProxies:
          - 10.0.0.0/16
        auth:
          mode: trusted-proxy
          trustedProxy:
            userHeader: X-Authentik-Email
            requiredHeaders:
              - X-Authentik-Username
              - X-Authentik-Uid
  envFrom:
    - secretRef:
        name: agent-secret
  security:
    networkPolicy:
      allowedIngressNamespaces:
        - traefik
  storage:
    persistence:
      existingClaim: agent-data
  extraVolumes:
    - name: shared
      hostPath:
        path: /mnt/local/openclaw/shared
        type: DirectoryOrCreate
  extraVolumeMounts:
    - name: shared
      mountPath: /shared
  gateway:
    existingSecret: agent-gateway-token
    controlUiOrigins:
      - https://openclaw.starry.blue
  runtimeDeps:
    pnpm: true
    python: true
  chromium:
    enabled: true
    image:
      repository: ghcr.io/browserless/chromium
      tag: v2.42.0
      digest: sha256:09648c90e8f986467db16978a822e9d698e1d4dcfea7fe0b04e5283971d668fe
  selfConfigure:
    enabled: true
    allowedActions:
      - skills
      - config
      - workspaceFiles
      - envVars
