apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: agent-secret

spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/6b6ktvirfs44nnfyafs7uix3v4

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: agent-gateway-token

spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/hf6rviwmifadasmhzvhdos3lhe
