apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: route

spec:
  routes:
    - kind: Rule
      match: Host(`n8n.starry.blue`)
      services:
        - name: n8n
          port: http
