apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: n8n-secret

spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/fq5kzyjkypzdrzg2s3zn5yuqnm

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgresql-secret

spec:
  itemPath: vaults/4mogpcwrvtvsnpooum4vcevwkm/items/wou3yx5aq227mjx7qctmfdkuse
