apiVersion: v1
kind: Service
metadata:
  name: postgresql

spec:
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/name: postgresql
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql

---
# StatefulSet の serviceName は不変なので、チャートが作っていた headless Service の名前を維持する
apiVersion: v1
kind: Service
metadata:
  name: postgresql-hl

spec:
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/name: postgresql
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  clusterIP: None
  publishNotReadyAddresses: true
