apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-postgresql-backup
spec:
  selector:
    matchLabels:
      name: n8n-postgresql-backup
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-postgresql-backup
  labels:
    name: n8n-postgresql-backup

spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  local:
    path: /mnt/local/n8n/postgresql-backup
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - lily
  persistentVolumeReclaimPolicy: Retain
