apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: endfield-auto
          image: ghcr.io/torikushiii/endfield-auto:latest@sha256:ac088d77ec7c6d83dfa16c12e72b0300fd8d2d1cb9f9ee9c774d1f2f466d7e21
          env:
            - name: TZ
              value: Asia/Tokyo
          volumeMounts:
            - name: config
              mountPath: /app/config.json
            - name: skport
              mountPath: /app/.skport
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: config
          hostPath:
            path: /mnt/local/endfield-auto/config.json
            type: File
        - name: skport
          emptyDir: {}
      restartPolicy: Always
      securityContext:
        seccompProfile:
          type: RuntimeDefault
