apiVersion: authentik.starry.blue/v1alpha1
kind: AuthentikApplication
metadata:
  name: mahiron

spec:
  access:
    rules:
      - user:
          username: github-actions-tvtest-distribution
      - group:
          name: Nerd
  adopt: IfMatch
  group: DTV
  icon: https://github.com/rokoucha/Mahiron/raw/refs/heads/main/web/src/assets/brand/icon.svg
  name: Mahiron
  provider:
    name: Mahiron
    flows:
      authentication:
        slug: sign-in
      authorization:
        slug: authorize
      invalidation:
        slug: default-provider-invalidation-flow
    proxy:
      accessTokenValidity: days=1
      forwardAuthSingle:
        externalHost: https://mahiron.starry.blue
      interceptHeaderAuth: true
      outpost:
        name: authentik Embedded Outpost
      refreshTokenValidity: days=30
  slug: mahiron
