apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: app
          image: orbforge/orb:latest@sha256:99d6eb7747c7cc2e80f6ddd933b9e6b3f29230c901e0d8c95655239cccffb83b
          volumeMounts:
            - name: data
              mountPath: /root/.config/orb
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_RAW
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: data
          hostPath:
            path: /mnt/local/orb/data
            type: DirectoryOrCreate
      restartPolicy: Always
      hostNetwork: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
