apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: app
          image: orbforge/orb:latest@sha256:bd4ff68ce52a417d69cabe871a940007afe7bfad92584a792e810257397d7b2c
          volumeMounts:
            - name: data
              mountPath: /root/.config/orb
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_RAW
      volumes:
        - name: data
          hostPath:
            path: /mnt/local/orb/data
            type: DirectoryOrCreate
      restartPolicy: Always
      hostNetwork: true
