apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: app
          image: orbforge/orb:latest@sha256:0e9367d4e547e063d0cd04722d98b15293d9438ec181782586151b29a1b336a2
          volumeMounts:
            - name: data
              mountPath: /root/.config/orb
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_RAW
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: data
          hostPath:
            path: /mnt/local/orb/data
            type: DirectoryOrCreate
      restartPolicy: Always
      hostNetwork: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
