apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis

spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: app
          image: public.ecr.aws/docker/library/redis:7.4.1-bookworm@sha256:d941b1988d3d75bf1a3d5c2b78a75806f59627a7a22db681a65f33e81f3f794d
          ports:
            - containerPort: 6379
          securityContext:
            allowPrivilegeEscalation: false
      restartPolicy: Always
