apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis

spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: app
          image: public.ecr.aws/docker/library/redis:8.4.0-bookworm@sha256:43355efd22490e31ca14b9d569367d05121e2be61fd8e47937563ae2a80952ae
          ports:
            - containerPort: 6379
          securityContext:
            allowPrivilegeEscalation: false
      restartPolicy: Always
