apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: app
          image: ghcr.io/slashnephy/kuroda-bot:master@sha256:15acf548d69aa85c69be3d19a1396371fe5970d8288d8fb779b897c435f68df8
          envFrom:
            - secretRef:
                name: app-secret
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      restartPolicy: Always
      securityContext:
        seccompProfile:
          type: RuntimeDefault
