apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana-alloy

helmCharts:
  - name: alloy
    releaseName: alloy
    namespace: grafana-alloy
    version: 1.7.0
    repo: https://grafana.github.io/helm-charts
    includeCRDs: true
    valuesInline:
      alloy:
        configMap:
          name: config
          create: false
          key: config.alloy
        mounts:
          varlog: true

resources:
  - ./resources/dns.yaml
  - ./resources/ingress.yaml
configMapGenerator:
  - name: config
    files:
      - ./config/config.alloy
    options:
      disableNameSuffixHash: true
