apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-infra

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: infra
  template:
    metadata:
      labels:
        app: infra
    spec:
      containers:
        - name: river-ui
          image: ghcr.io/riverqueue/riverui:0.19.0@sha256:cf7f314227164664af529658b7c83b0746d70e68da17684fd24df0baa6394fad
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: JOB_QUEUE_DSN
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      restartPolicy: Always
      securityContext:
        seccompProfile:
          type: RuntimeDefault
