apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob

spec:
  schedule: "0 * * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: app
              image: alpine/kubectl:1.36.3@sha256:1f0c86385ebec294558b450956a390116c098d04166bb279b7c9776082b339eb
              command:
                - /bin/ash
                - -c
                - |
                  kubectl get secrets -A -o yaml > /backup/secrets_$(date +%Y%m%d).yaml
                  kubectl get configmaps -A -o yaml > /backup/configmaps_$(date +%Y%m%d).yaml
              volumeMounts:
                - name: backup
                  mountPath: /backup
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
          volumes:
            - name: backup
              hostPath:
                path: /mnt/local/backup-node
                type: DirectoryOrCreate
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          serviceAccountName: service-account
  concurrencyPolicy: Forbid
