apiVersion: batch/v1
kind: CronJob
metadata:
  name: music-gdrive

spec:
  schedule: "*/15 * * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: app
              image: rclone/rclone:1.74.4@sha256:c61954aaa32328a5486715dd063a81c7879f5195ad3505cd362deddd509dc4a1
              args:
                - sync
                - "unicorn:"
                - /mnt/pool/music/sync
                - --order-by=name
                - --config=/config/rclone/rclone.conf
                - --log-level=INFO
              volumeMounts:
                - name: mnt
                  mountPath: /mnt
                - name: config
                  mountPath: /config/rclone
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
                runAsGroup: 1000
                runAsUser: 1000
          volumes:
            - name: mnt
              hostPath:
                path: /mnt
                type: Directory
            - name: config
              hostPath:
                path: /mnt/local/rclone-config
                type: Directory
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
