apiVersion: batch/v1
kind: CronJob
metadata:
  name: music

spec:
  schedule: "*/15 * * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: app
              image: rclone/rclone:1.73.4@sha256:654f6517c7aaec7e377690b2caf7c272dbe5f3b8200afbc14a00df6b4a9aa6ef
              args:
                - sync
                - /mnt/pool/music
                - Neotopia:Music/share
                - --order-by=name
                - --config=/config/rclone/rclone.conf
                - --log-level=INFO
              volumeMounts:
                - name: mnt
                  mountPath: /mnt
                  readOnly: true
                - name: config
                  mountPath: /config/rclone
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
                runAsGroup: 1000
                runAsUser: 1000
          volumes:
            - name: mnt
              hostPath:
                path: /mnt
                type: Directory
            - name: config
              hostPath:
                path: /mnt/local/rclone-config
                type: Directory
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
