apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: app
          image: ghcr.io/tsukumijima/konomitv:latest@sha256:e6f45e08aab780ce7553d4eafe65ada239619ce2a2d3beb9732e03b9bbcad4f1
          volumeMounts:
            - name: config
              mountPath: /code/config.yaml
              readOnly: true
              subPath: config.yaml
            - name: data
              mountPath: /code/server/data
            - name: records
              mountPath: /mnt/records
              readOnly: true
            - name: records-local
              mountPath: /mnt/records_local
              readOnly: true
            - name: logs
              mountPath: /code/server/logs
          resources:
            limits:
              gpu.intel.com/i915: "1"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: config
          configMap:
            name: app-config
        - name: data
          hostPath:
            path: /mnt/local/konomitv/data
            type: DirectoryOrCreate
        - name: records
          hostPath:
            path: /mnt/pool/records
            type: Directory
        - name: records-local
          hostPath:
            path: /mnt/pool/records_local
            type: Directory
        - name: logs
          emptyDir: {}
      restartPolicy: Always
      securityContext:
        seccompProfile:
          type: RuntimeDefault
