apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-webui

helmCharts:
  # https://github.com/open-webui/helm-charts
  - name: open-webui
    releaseName: open-webui
    namespace: open-webui
    version: 12.10.0
    repo: https://helm.openwebui.com
    valuesInline:
      extraEnvVars:
        - name: TZ
          value: Asia/Tokyo
        - name: ENABLE_SIGNUP
          value: "false"
        - name: ENABLE_LOGIN_FORM
          value: "false"
      ollama:
        enabled: false
      persistence:
        enabled: true
        existingClaim: open-webui-data
      pipelines:
        enabled: false
      sso:
        enableSignup: true
        enabled: true
        groupManagement:
          groupsClaim: groups
        oidc:
          clientExistingSecret: open-webui-secret
          clientExistingSecretKey: OAUTH_CLIENT_SECRET
          clientId: nw61bxl1f9J6HvojXaja3MwxmtfXL15BvwwUw5Bp
          enabled: true
          providerName: id.starry.blue
          providerUrl: https://id.starry.blue/application/o/open-web-ui/.well-known/openid-configuration
          scopes: openid email profile

resources:
  - ./resources/dns.yaml
  - ./resources/ingress.yaml
  - ./resources/secret.yaml
  - ./resources/volume.yaml
