apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-webui

helmCharts:
  # https://github.com/open-webui/helm-charts
  - name: open-webui
    releaseName: open-webui
    namespace: open-webui
    version: 12.10.0
    repo: https://helm.openwebui.com
    valuesInline:
      extraEnvVars:
        - name: TZ
          value: Asia/Tokyo
      ollama:
        enabled: false
      persistence:
        enabled: true
        existingClaim: open-webui-data
      pipelines:
        enabled: false

resources:
  - ./resources/volume.yaml
  - ./resources/ingress.yaml
  - ./resources/dns.yaml
