apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana-loki

helmCharts:
  - name: loki
    releaseName: loki
    namespace: grafana-loki
    version: 6.57.0
    repo: oci://ghcr.io/grafana-community/helm-charts
    includeCRDs: true
    valuesInline:
      backend:
        replicas: 0
      deploymentMode: SingleBinary
      gateway:
        enabled: false

      loki:
        auth_enabled: false
        commonConfig:
          replication_factor: 1
        compactor:
          compaction_interval: 10m
          delete_request_store: filesystem
          retention_enabled: true
        frontend:
          max_outstanding_per_tenant: 4096
        limits_config:
          max_query_parallelism: 32
          max_query_series: 100000
          retention_period: 720h  # 30 days
          split_queries_by_interval: 15m
        query_scheduler:
          max_outstanding_requests_per_tenant: 4096
        schemaConfig:
          configs:
            - from: 2024-04-01
              index:
                period: 24h
                prefix: loki_index_
              object_store: filesystem
              schema: v13
              store: tsdb
        storage:
          bucketNames:
            chunks: []
          type: filesystem
      lokiCanary:
        enabled: false
      read:
        replicas: 0
      singleBinary:
        persistence:
          selector:
            matchLabels:
              name: grafana-loki-data
          storageClass: local
        replicas: 1
      test:
        enabled: false
      write:
        replicas: 0
resources:
  - ./resources/volume.yaml
