name: Deploy watch-k8s-events

on:
  push:
    paths:
      - cmd/watch-k8s-events/**
  workflow_dispatch:

permissions: {}

jobs:
  build:
    uses: SlashNephy/actions/.github/workflows/build-docker-image.yml@cf12e2d382df42d9fcfc4ee94f901661d8255d19 # v0.0.7
    permissions:
      contents: read
      packages: write
      actions: read
      security-events: write
    with:
      context: cmd/watch-k8s-events
      image-name: ghcr.io/slashnephy/watch-k8s-events
      image-platforms: linux/amd64
      dispatch-update-image-digest: true
    secrets:
      dispatch-github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
