name: Deploy wait-for

on:
  push:
    paths:
      - cmd/wait-for/**
  workflow_dispatch:

permissions: {}

jobs:
  build:
    uses: SlashNephy/actions/.github/workflows/build-docker-image.yml@6c1e1155e0a1b5aaf975544e23d7ff490511a1d9 # v0.0.6
    permissions:
      contents: read
      packages: write
      actions: read
      security-events: write
    with:
      context: cmd/wait-for
      image-name: ghcr.io/slashnephy/wait-for
      image-platforms: linux/amd64
      dispatch-update-image-digest: true
    secrets:
      dispatch-github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
