name: Deploy restart-epgstation-deployment

on:
  push:
    paths:
      - cmd/restart-epgstation-deployment/**
  workflow_dispatch:

permissions: {}

jobs:
  build:
    uses: SlashNephy/actions/.github/workflows/build-docker-image.yml@f63926caa7aad32744d96b2129d04ea0d549e9fb # v0.0.5
    permissions:
      contents: read
      packages: write
      actions: read
      security-events: write
    with:
      context: cmd/restart-epgstation-deployment
      image-name: ghcr.io/slashnephy/restart-epgstation-deployment
      image-platforms: linux/amd64
      dispatch-update-image-digest: true
    secrets:
      dispatch-github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
