name: Deploy curl-jq

on:
  push:
    paths:
      - cmd/curl-jq/**
  workflow_dispatch:

permissions: {}

jobs:
  build:
    uses: SlashNephy/actions/.github/workflows/build-docker-image.yml@d5bbbb58e94f3b25497f996ea141b31d6db26857 # v1.0.1
    permissions:
      contents: read
      packages: write
      actions: read
      security-events: write
    with:
      context: cmd/curl-jq
      image-name: ghcr.io/slashnephy/curl-jq
      image-platforms: linux/amd64
      dispatch-update-image-digest: true
    secrets:
      dispatch-app-private-key: ${{ secrets.DISPATCH_APP_PRIVATE_KEY }}
