name: Deploy watch-k8s-events

on:
  push:
    paths:
      - cmd/watch-k8s-events/**
  workflow_dispatch:

permissions: {}

jobs:
  build:
    uses: SlashNephy/actions/.github/workflows/build-docker-image.yml@70aa7999543c0745815c8233fd18fc1759748f6c # v1.0.0
    permissions:
      contents: read
      packages: write
      actions: read
      security-events: write
    with:
      context: cmd/watch-k8s-events
      image-name: ghcr.io/slashnephy/watch-k8s-events
      image-platforms: linux/amd64
      dispatch-update-image-digest: true
    secrets:
      dispatch-app-private-key: ${{ secrets.DISPATCH_APP_PRIVATE_KEY }}
