name: KubeLinter

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
      - name: kube-linter
        run: |
          kube-linter lint \
            --format sarif \
            --output kube-linter.sarif \
            --config .kube-linter.yaml \
            ./k8s || true
      - uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        if: always()
        with:
          sarif_file: kube-linter.sarif
          category: kube-linter
