name: 'Lint *.yml'

on:
  push:
    branches:
      - master
    paths:
      - '**/*.yml'
      - '**/*.yaml'

  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**/*.yml'
      - '**/*.yaml'

  workflow_dispatch:

jobs:
  lint:
    uses: SlashNephy/.github/.github/workflows/yamllint.yml@2b64691f87d64d627f89946fb6f21169ddffc8b0 # master
    permissions:
      contents: read
      pull-requests: write
