apiVersion: v1
kind: PersistentVolume
metadata:
  name: qdrant-storage
  labels:
    name: qdrant-storage

spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    namespace: qdrant
    name: qdrant-data-qdrant-0
  local:
    path: /mnt/local/qdrant/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - lily
  persistentVolumeReclaimPolicy: Retain
