apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-data

spec:
  selector:
    matchLabels:
      name: qdrant-data
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qdrant-data
  labels:
    name: qdrant-data

spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /mnt/local/qdrant/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - lily
  persistentVolumeReclaimPolicy: Retain
